export const GAME_ELEMENT_ID_PREFIX = "BRACKET-GAME-";
export const BRACKET_CONTAINER_ELEMENT_ID_PREFIX = "BRACKET-CONTAINER-";
export const BRACKET_GAME = "BRACKET_GAME";
export const BRACKET_GAME_FINAL_RESULT = "BRACKET_GAME_FINAL_RESULT";
